services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  service-a:
    image: golang:latest
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - SERVICE_A_PORT=8080
      - SERVICE_B_PORT=8081
      - SERVICE_B_HOST=service-b
    volumes:
      - .:/app
    command: >
      sh -c "
      cd /app &&
      go mod tidy &&
      GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/service-a ./cmd/service-a/main.go &&
      ./build/service-a"
    depends_on:
      - zipkin

  service-b:
    image: golang:latest
    container_name: service-b
    ports:
      - "8081:8081"
    environment:
      - SERVICE_B_PORT=8081
      - WEATHER_API_KEY=fb9f540724614991af651016242806
    volumes:
      - .:/app
    command: >
      sh -c "
      cd /app && 
      go mod tidy &&
      GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/service-b ./cmd/service-b/main.go &&
      ./build/service-b"
    depends_on:
      - zipkin