services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  service-a-zipcode:
    image: golang:latest
    container_name: service-a-zipcode
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SERVICE_A_PORT=8080
    volumes:
      - .:/app
    command: >
      sh -c "
      cd /app &&
      go mod tidy &&
      GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/service-a-zipcode ./service-a-zipcode/cmd/main.go &&
      ./build/service-a-zipcode"
    depends_on:
      - zipkin

  service-b-weather:
    image: golang:latest
    container_name: service-b-weather
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SERVICE_B_PORT=8081
      - SERVICE_A_HOST=service-a-zipcode
      - SERVICE_A_PORT=8080
      - KEY_WEATHER_API=fb9f540724614991af651016242806
    volumes:
      - .:/app
    command: >
      sh -c "
      cd /app && 
      go mod tidy &&
      GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/service-b-weather ./service-b-weather/cmd/main.go &&
      ./build/service-b-weather"
    depends_on:
      - zipkin